image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y gfortran 
  - apt-get install -y libatlas-base-dev 
  - apt-get install -y mpich 
  - apt-get install -y make
stages:
  - build
  - test
  
Compile_the_ode:
  stage: build
    - cd f90
    - make -f Makefile3D_MT_GFortran
  
Test_the_ode:
  stage: test
  script:
    - cd ..
    - cd testing-folder
    - mpirun -n 2 ../f90/Mod3DMT -F pr.ws test_data_LatLongSites.dat test_pred.dat