#
# EXEC ORDER OF STAGES
stages:
    - build
    - test
    - deploy
#
#
# MAIN BEFORE SCRIPT
before_script:
        - echo "START MAIN SCRIPT"
#
# BUILD JOB: BUILD modem_on BINARY, STORE ON CACHE AND CREATE DOWNLOADABLE ARTIFACT
build_modem_on:
    stage: build    # DEFINES STAGE NATURE
    #
    before_script:
        - echo "START build_modem_on SCRIPT"
    #
    script:
        # GENERATE MAIN OUTPUT FOLDER (IF NOT EXISTS)
        - mkdir -p outputs/
        # BUILD SCRIPT
        - bash scripts/build_modem_on.sh &>> outputs/build_modem_on.txt
        # GENERATE DOCS FOLDER (IF NOT EXISTS)
        - mkdir -p docs/
        # RUN DOXYGEN ON src/
        - bash scripts/update_doxygen.sh &>> outputs/update_doxygen.txt
    #
    cache:
        key: build_modem_on_cache   # CACHE KEY TO ACCESS FROM OTHERS JOBS
        paths:
            - src/Mod3DMT   # PATH TO BE UPLOADED
            - outputs/
            - docs/
    #
    artifacts:
        paths:
            - src/Mod3DMT   # PATH TO BE UPLOADED
            - outputs
            - docs
        expire_in: 1 week
    #
    after_script:
        - echo "FINISH build_modem_on"
#
# JOB TEST PLAIN:   RUN Mod3DMT WITHOUT ANY PARAMETER
.test_plain:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        # PLAIN EXECUTION TEST
        - bash scripts/test_plain.sh &>> test_plain.txt
    #
    artifacts:
        paths:
            - outputs/test_plain.txt
        expire_in: 1 week
#
# STANDART TEST READ_WRITE
.test_read_write:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        - bash scripts/test_read_write.sh src/Mod3DMT inputs/rFile_Model.ws inputs/rFile_Data.dat
    #
    artifacts:
        paths:
            - outputs/test_read_write/
        expire_in: 1 week
#
# STANDART TEST FORWARD
.test_forward:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        - bash scripts/test_forward.sh src/Mod3DMT inputs/rFile_Model.ws inputs/rFile_Data.dat
    #
    artifacts:
        paths:
            - outputs/test_forward/
        expire_in: 1 week
#
# STANDART TEST COMPUTE_J
.test_compute_j:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        - bash scripts/test_compute_j.sh src/Mod3DMT inputs/rFile_Model.ws inputs/rFile_Data.dat
    #
    artifacts:
        paths:
            - outputs/test_compute_j/
        expire_in: 1 week
#
# STANDART TEST INVERSE
test_mult_by_j_t:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        - bash scripts/test_mult_by_j_t.sh src/Mod3DMT inputs/rFile_Model.ws inputs/rFile_Data.dat
    #
    artifacts:
        paths:
            - outputs/test_mult_by_j_t/
        expire_in: 1 week
#
# STANDART TEST INVERSE
.test_inverse:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        - bash scripts/test_inverse.sh src/Mod3DMT inputs/rFile_Model.ws inputs/rFile_Data.dat
    #
    artifacts:
        paths:
            - outputs/test_inverse/
        expire_in: 1 week
#
# STANDART TEST COV
.test_cov:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        - bash scripts/test_cov.sh src/Mod3DMT inputs/rFile_Model.ws
    #
    artifacts:
        paths:
            - outputs/test_cov/
        expire_in: 1 week
#
# TEST JOB 3:   RUN EVERY TEST AT tests/ DIR
.test_engine_modem_on:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        # USER DEFINED TESTS
        - bash scripts/test_engine.sh src/Mod3DMT
        #
    artifacts:
        paths:
            - outputs/
        expire_in: 1 week
#
# DEPLOY: UPDATE GITLAB
update_gitlab:
    stage: deploy
    environment: production
    script:
        #
        # BASH: UPDATES GITLAB
        - bash scripts/update_gitlab.sh &>> outputs/update_gitlab.txt
#
# DEPLOY: UPDATE PAGES
.pages:
    stage: deploy
    environment: staging
    script:
        #
        # BASH: PAGE UPDATES
        - bash scripts/update_pages.sh
        #
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
#
# END MAIN SCRIPT