image: ubuntu:14.04

before_script:
  - apt-get update
  - apt-get install -y gcc g++
  - apt-get install gfortran
stages:
  - build

cache:
  paths:
    - f90/

install_dependencies:
  stage: build
  script:
    - make