image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install gfortran 
  - apt-get install libatlas-base-dev 
  - apt-get install libmpich2-dev 
  - apt-get install make

job1:
  script:
    - cd f90
    - make -f Makefile3d