image: ubuntu:14.04

before_script:
  - apt-get update
  - apt-get install -y gcc g++
stages:
  - build
  - test
  - test2

cache:
  paths:
    - f90/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: test
  script: npm test