image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y gfortran 
  - apt-get install -y libatlas-base-dev 
  - apt-get install -y mpich 
  - apt-get install -y make

job1:
  script:
    - cd f90
    - make -f Makefile3D_MT_GFortran