#
# EXEC ORDER OF STAGES
stages:
    - build
    - test
    - deploy
#
#
# MAIN BEFORE SCRIPT
before_script:
        - echo "START MAIN SCRIPT"
#
# BUILD JOB: BUILD modem_on BINARY, STORE ON CACHE AND CREATE DOWNLOADABLE ARTIFACT
build_modem_on:
    stage: build    # DEFINES STAGE NATURE
    #
    before_script:
        - echo "START build_modem_on SCRIPT"
    #
    script:
        # GENERATE BIN FOLDER (IF NOT EXISTS)
        - mkdir -p bin
        # GENERATE MAIN OUTPUT FOLDER (IF NOT EXISTS)
        - mkdir -p outputs/temp
        # BUILD SCRIPT
        - bash scripts/build_modem_on.sh | tee outputs/temp/build_modem_on.txt
        # GENERATE DOCS FOLDER (IF NOT EXISTS)
        - mkdir -p docs/
        # RUN DOXYGEN ON src/
        - bash scripts/update_doxygen.sh | tee outputs/temp/update_doxygen.txt
    #
    cache:
        key: build_modem_on_cache   # CACHE KEY TO ACCESS FROM OTHERS JOBS
        paths:
            - bin/
            - outputs/temp/
            - docs/
    #
    artifacts:
        paths:
            - bin/
            - outputs/temp/
            - docs
        expire_in: 1 week
    #
    after_script:
        - echo "FINISH build_modem_on"
#
# JOB TEST PLAIN STD:   RUN Mod3DMT STD WITHOUT ANY PARAMETER
test_plain_std:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        # PLAIN EXECUTION TEST WITH 1 CORE
        - bash scripts/test_plain.sh bin/Mod3DMT_STD 1
    #
    artifacts:
        paths:
            - outputs/temp/test_plain*
        expire_in: 1 week
#
# JOB TEST PLAIN SP2:   RUN Mod3DMT SP2 WITHOUT ANY PARAMETER
test_plain_sp2:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        # PLAIN EXECUTION TEST WITH 1 CORE
        - bash scripts/test_plain.sh bin/Mod3DMT_SP2 1
    #
    artifacts:
        paths:
            - outputs/temp/test_plain*
        expire_in: 1 week
#
# STANDART TEST READ_WRITE STD
test_read_write_std:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        - bash scripts/test_read_write.sh bin/Mod3DMT_STD inputs/rFile_Model inputs/rFile_Data 1
    #
    artifacts:
        paths:
            - outputs/temp/test_read_write*
        expire_in: 1 week
#
# STANDART TEST READ_WRITE STD
test_read_write_sp2:
    stage: test
    dependencies:
        - build_modem_on    # DEFINE THIS JOB DEPENDENCY FROM JOB build_modem_on
    #
    script:
        #
        - bash scripts/test_read_write.sh bin/Mod3DMT_SP2 inputs/rFile_Model inputs/rFile_Data 1
    #
    artifacts:
        paths:
            - outputs/temp/test_read_write*
        expire_in: 1 week
#
# DEPLOY: UPDATE GITLAB
update_gitlab:
    stage: deploy
    environment: production
    script:
        #
        # REMOVE BINARIES
        - rm -rf bin/
        #
        # CREATE FOLDER UNIQUE NAME
        - output_folder=output_$(date "+%Y_%m_%d_%H_%M_%S")
        #
        # CHANGE TEMP NAME
        - mv outputs/temp outputs/$output_folder
        #
        # BASH: UPDATES GITLAB
        - bash scripts/update_gitlab.sh $CI_COMMIT_REF_NAME | tee outputs/$output_folder/update_gitlab.txt
        #
    #
    artifacts:
        paths:
            - outputs/$output_folder/
        expire_in: 1 week
    #only:
        #- master
#
# DEPLOY: UPDATE PAGES
pages:
    stage: deploy
    environment: staging
    script:
        #
        # BASH: PAGE UPDATES
        - bash scripts/update_pages.sh
        #
    artifacts:
        paths:
            - public
        expire_in: 30 days
    #only:
        #- master
#
# END MAIN SCRIPT