image: ubuntu:14.04

before_script:
  - apt-get install gfortran
  - apt-get install libatlas-base-dev
  - apt-get install libmpich2-dev
stages:
  - build
  - test
  - test2

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: test
  script: npm test