"""
Same-physical-latitude validation of the EGBERTKELBERT2012_MODEM preset.

Separates any latitude-sampling artifact from the genuine normalization
residual in the global1d-vs-ModEM comparison. Two facts make the comparison
subtle:
  - ModEM's per-column BC makes its surface field laterally ~uniform.
  - global1d's zonal (P10) field varies as sin(theta) about the (fake) pole,
    so it is maximal at the fake equator and smaller elsewhere.
The correct comparison is therefore ModEM (anywhere) vs global1d at its
sin(theta)=1 maximum (the fake equator). This script (a) confirms global1d's
sin(theta) latitude dependence, (b) checks ModEM's lateral uniformity, and
(c) reports the residual r = E_g1d(equator)/mean(E_ModEM).

Result (this model/grid): the interior comparison point is ALREADY at the
fake equator, so there is NO latitude-sampling artifact; the ~1.5% ModEM
lateral spread is the only sampling effect. The remaining residual
(|r| ~ 0.93-1.01 amplitude, +0.2..+5.2 deg phase over T=10..1000 s) is a
genuine model difference (finite-Q C-response + ModEM's discrete-air-layer
flat BC vs global1d's spherical solution), not a convention artifact.

Inputs (both LOCAL to this directory, generated by run_spherical_comparison.sh):
  out.esoln                                 -- spherical ModEM (USA_small)
  normchk.s1.EGBERTKELBERT2012_MODEM.esoln  -- global1d 3-period (default preset)

Usage:
  bash run_spherical_comparison.sh   # generates both .esoln (needs ModEM+FWD1D) then runs this
  python analyze_samepoint.py        # re-run on already-generated .esoln
Only external dependency: compiled Mod3DMT_SP2_SPH + FWD1D (paths in the driver header).
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + os.sep + '..')
import numpy as np
from read_esoln import read_esoln


def main():
    dm = read_esoln('out.esoln')
    dg = read_esoln('normchk.s1.EGBERTKELBERT2012_MODEM.esoln')
    k = 12  # surface (k=13, 1-indexed)

    def byom(d, im):
        return {round(b['omega'], 8): b for b in d['blocks'] if b['iMode'] == im}
    mm, gg = byom(dm, 1), byom(dg, 1)

    print('  T(s)   |r| (amp)   arg (phase)   ModEM lateral spread   [r = E_g1d(equator)/mean(E_ModEM)]')
    for om in sorted(mm.keys(), reverse=True):
        if om not in gg:
            continue
        T = 2 * np.pi / om
        Em, Eg = mm[om]['Ey'], gg[om]['Ey']
        j = Eg.shape[1] // 2
        mvals = np.array([Em[i, jj, k] for i in range(1, dm['nx'])
                          for jj in range(1, dm['ny'] - 1)])
        spread = np.std(np.abs(mvals)) / abs(np.mean(mvals)) * 100
        mmean = np.mean(mvals)                          # ModEM uniform field
        ieq = np.argmax(np.abs(Eg[:, j, k]))           # global1d fake equator (sin th=1)
        r = Eg[ieq, j, k] / mmean
        print(f' {T:7.1f}   {abs(r):.3f}      {np.degrees(np.angle(r)):+5.1f} deg     {spread:.2f}%')


if __name__ == '__main__':
    main()
