#!/bin/bash
# =============================================================================
# Generate Halfspace.rho: a Cartesian WS3D model file for ModEM -- a 48x68x44
# grid (dx,dy in metres; dz geometric) of UNIFORM rho = 100 ohm.m (stored as
# LOGE = ln(100) = 4.60517). Byte-compatible with ModEM's own
# debug-serial/CylinderModel/Halfspace.rho, so the Cartesian sanity check
# (run_cartesian_sanity.sh) is self-contained without committing the 2.1 MB
# model file. ModEM adds the air layers itself per Halfspace.fwd (12 layers,
# 1000 km top).
#
#   bash make_halfspace_rho.sh      # writes ./Halfspace.rho
# =============================================================================
set -e
cd "$(dirname "$0")"
out=Halfspace.rho

NX=48; NY=68; NZ=44
# lateral cell widths (m): 4 stretched padding cells (decreasing) + uniform 10 km
# core + 4 padding (increasing, the mirror of the left)
PADL="99456 61040 33600 14000"
PADR="14000 33600 61040 99456"
DX="$PADL $(printf '10000 %.0s' $(seq 1 40))$PADR"    # 4 + 40 + 4 = 48
DY="$PADL $(printf '10000 %.0s' $(seq 1 60))$PADR"    # 4 + 60 + 4 = 68
# vertical layer thicknesses (m), geometric growth (44 layers):
DZ="28.2565 33.9078 40.6894 48.8272 58.5927 70.3112 84.3734 101.248 121.498 \
145.797 174.957 209.948 251.938 302.325 362.79 435.348 522.418 626.902 752.282 \
902.738 1083.29 1299.94 1559.93 1871.92 2246.3 2695.56 3234.68 3881.61 4657.93 \
5589.52 6707.42 8048.91 9658.69 11590.4 13908.5 16690.2 18271.2 27406.8 41110.2 \
61665.3 92498 138747 208121 312181"
RHO="4.60517E+00"                                     # LOGE of 100 ohm.m

ROW=$(printf "$RHO %.0s" $(seq 1 $NX))                # one grid row: NX identical values
{
  echo "# Generated by make_halfspace_rho.sh -- uniform rho=100 ohm.m halfspace"
  echo "$NX $NY $NZ 0 LOGE"
  echo "$DX"
  echo "$DY"
  echo "$DZ"
  for iz in $(seq 1 $NZ); do
    echo ""                                           # blank line before each z-slice
    for iy in $(seq 1 $NY); do echo "$ROW"; done      # NY rows of NX values
  done
  echo "-200000 -300000 0"                            # origin (ox oy oz)
  echo "0"                                            # rotation angle
} > "$out"

echo "wrote $out ($NX x $NY x $NZ, uniform rho=100 ohm.m)"
