#!/bin/bash
# =============================================================================
# Self-contained Cartesian-ModEM sanity check of the G / EGBERTKELBERT2012_MODEM
# source-normalization (see cartesian_sanity_check.md, docs/source_normalization.md
# sec.6). Cartesian ModEM is trusted/accurate; the spherical build is experimental
# (needs FORCE_SPHERICAL), so this cross-checks the whole framework on trusted code.
#
# Run in WSL / Linux (the ModEM and FWD1D binaries are Linux ELF):
#     wsl bash run_cartesian_sanity.sh          # from Windows PowerShell, or
#     bash run_cartesian_sanity.sh              # from a WSL shell in this directory
#
# The ONLY external dependencies are the two compiled binaries below -- everything
# else (Halfspace.rho is generated by make_halfspace_rho.sh; Halfspace.fwd,
# halfspace_template.dat, halfspace.prm, p10_halfspace.prm live in this directory;
# the global1d grid/model are in the repo).
# =============================================================================
set -e
cd "$(dirname "$0")"

# -------------------- external binaries: EDIT THESE PATHS --------------------
MODEM_CART=../../../ModEM/build-serial/Mod3DMT_SP2     # trusted Cartesian ModEM (-F forward)
FWD1D=../../FWD1D                                      # global1d forward solver (default preset)
# -----------------------------------------------------------------------------
GRID=../../MTsource/USA.0.25x0.25.grd

echo "[1/4] generate the Cartesian halfspace model -> Halfspace.rho"
bash make_halfspace_rho.sh

echo "[2/4] Cartesian ModEM forward on the rho=100 halfspace -> out_cart.esoln"
"$MODEM_CART" -F Halfspace.rho halfspace_template.dat out_cart.dat out_cart.esoln Halfspace.fwd

echo "[3/4] global1d halfspace, default EGBERTKELBERT2012_MODEM preset, fake pole (0,90) -> hs.*.esoln"
"$FWD1D" halfspace.prm p10_halfspace.prm "$GRID" hs 0 90

echo "[4/4] analysis (needs a python with numpy+scipy):"
python analyze_cartesian.py \
  || echo ">> .esoln generated. Now run:  python analyze_cartesian.py  (with your scipy-enabled python)"
