# Makefile for test_unit_sphere, the field1d.f90 validation test.
# Mirrors Makefile1d but only builds the field1d.f90 dependency chain
# (utilities, polpak, GridDef, sg_vector) -- no ModelSpace/LAPACK needed.
#
# Lives in a "testing" subdirectory one level below the repo root
# (i.e. alongside FWD1D.f90, Makefile1d, Makefile.local, UTILS/, EARTH/, FIELDS/).
# ROOT below is the only path that needs to change if you move this file
# somewhere else relative to the repo root.
#
# Usage (from within testing/):
#   make -f Makefile.test1d
#   ./test_unit_sphere

ROOT = ..

include $(ROOT)/Makefile.local
OBJDIR = ./objs/test1d
F90 = gfortran
FFLAGS = -O2 -g -fbacktrace -fbounds-check
MPIFLAGS = -cpp
MODULE = -J$(OBJDIR)

OBJ = $(OBJDIR)/math_constants.o $(OBJDIR)/utilities.o $(OBJDIR)/polpak.o \
      $(OBJDIR)/file_units.o $(OBJDIR)/GridDef.o $(OBJDIR)/sg_vector.o \
      $(OBJDIR)/field1d.o $(OBJDIR)/test_unit_sphere.o

all: test_unit_sphere

test_unit_sphere: $(OBJDIR) $(OBJ)
	$(F90) -o test_unit_sphere $(OBJ)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/math_constants.o: $(ROOT)/UTILS/math_constants.f90
	$(F90) -c $(MODULE) $(FFLAGS) $(MPIFLAGS) $(ROOT)/UTILS/math_constants.f90 -o $(OBJDIR)/math_constants.o

$(OBJDIR)/utilities.o: $(ROOT)/UTILS/utilities.f90 $(OBJDIR)/math_constants.o
	$(F90) -c $(MODULE) $(FFLAGS) $(MPIFLAGS) $(ROOT)/UTILS/utilities.f90 -o $(OBJDIR)/utilities.o

$(OBJDIR)/polpak.o: $(ROOT)/UTILS/polpak.f90
	$(F90) -c $(MODULE) $(FFLAGS) $(MPIFLAGS) $(ROOT)/UTILS/polpak.f90 -o $(OBJDIR)/polpak.o

$(OBJDIR)/file_units.o: $(ROOT)/UTILS/file_units.f90
	$(F90) -c $(MODULE) $(FFLAGS) $(MPIFLAGS) $(ROOT)/UTILS/file_units.f90 -o $(OBJDIR)/file_units.o

$(OBJDIR)/GridDef.o: $(ROOT)/EARTH/GridDef.f90 $(OBJDIR)/math_constants.o $(OBJDIR)/file_units.o $(OBJDIR)/utilities.o
	$(F90) -c $(MODULE) $(FFLAGS) $(MPIFLAGS) $(ROOT)/EARTH/GridDef.f90 -o $(OBJDIR)/GridDef.o

$(OBJDIR)/sg_vector.o: $(ROOT)/FIELDS/FiniteDiff3D/sg_vector.f90 $(OBJDIR)/math_constants.o $(OBJDIR)/utilities.o $(OBJDIR)/GridDef.o
	$(F90) -c $(MODULE) $(FFLAGS) $(MPIFLAGS) $(ROOT)/FIELDS/FiniteDiff3D/sg_vector.f90 -o $(OBJDIR)/sg_vector.o

$(OBJDIR)/field1d.o: $(ROOT)/EARTH/FWD/field1d.f90 $(OBJDIR)/utilities.o $(OBJDIR)/polpak.o $(OBJDIR)/GridDef.o $(OBJDIR)/sg_vector.o
	$(F90) -c $(MODULE) $(FFLAGS) $(MPIFLAGS) $(ROOT)/EARTH/FWD/field1d.f90 -o $(OBJDIR)/field1d.o

$(OBJDIR)/test_unit_sphere.o: test_unit_sphere.f90 $(OBJDIR)/field1d.o
	$(F90) -c $(MODULE) $(FFLAGS) $(MPIFLAGS) test_unit_sphere.f90 -o $(OBJDIR)/test_unit_sphere.o

clean:
	rm -rf $(OBJDIR) test_unit_sphere
