#!/bin/bash
#
# mf_sg_qmr
#
mpirun -np 13 --hostfile ../../hostfile_13.txt ./ModEM_MPI -f -m ../../modem_inputs/Small_model/Starting_model_Small_v_4_h.rho -d ../../modem_inputs/Small_model/Data_on_Small_Grid_20%Err.dat -cf fwd_control_mf_sg_qmr.txt -pd pred_mf_sg_qmr.dat
#
# mf_sg_bicg
#
mpirun -np 13 --hostfile ../../hostfile_13.txt ./ModEM_MPI -f -m ../../modem_inputs/Small_model/Starting_model_Small_v_4_h.rho -d ../../modem_inputs/Small_model/Data_on_Small_Grid_20%Err.dat -cf fwd_control_mf_sg_bicg.txt -pd pred_mf_sg_bicg.dat
#
# sp_sg_qmr
#
mpirun -np 13 --hostfile ../../hostfile_13.txt ./ModEM_MPI -f -m ../../modem_inputs/Small_model/Starting_model_Small_v_4_h.rho -d ../../modem_inputs/Small_model/Data_on_Small_Grid_20%Err.dat -cf fwd_control_sp_sg_qmr.txt -pd pred_sp_sg_qmr.dat
#
# sp_sg_bicg
#
mpirun -np 13 --hostfile ../../hostfile_13.txt ./ModEM_MPI -f -m ../../modem_inputs/Small_model/Starting_model_Small_v_4_h.rho -d ../../modem_inputs/Small_model/Data_on_Small_Grid_20%Err.dat -cf fwd_control_sp_sg_bicg.txt -pd pred_sp_sg_bicg.dat
#
# sp2_sg_qmr
#
mpirun -np 13 --hostfile ../../hostfile_13.txt ./ModEM_MPI -f -m ../../modem_inputs/Small_model/Starting_model_Small_v_4_h.rho -d ../../modem_inputs/Small_model/Data_on_Small_Grid_20%Err.dat -cf fwd_control_sp2_sg_qmr.txt -pd pred_sp2_sg_qmr.dat
#
# sp2_sg_bicg
#
mpirun -np 13 --hostfile ../../hostfile_13.txt ./ModEM_MPI -f -m ../../modem_inputs/Small_model/Starting_model_Small_v_4_h.rho -d ../../modem_inputs/Small_model/Data_on_Small_Grid_20%Err.dat -cf fwd_control_sp2_sg_bicg.txt -pd pred_sp2_sg_bicg.dat
#